"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/fish/tasks"

ENDPOINTS = {
    "fish_generate_audio": {
        "method": "POST",
        "path": "/fish/tts",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["text"],
            "properties": {
                "text": {"type": "string"},
                "reference_id": {
                    "oneOf": [
                        {"type": "string"},
                        {"type": "array", "minItems": 1, "items": {"type": "string"}},
                    ]
                },
                "format": {"enum": ["mp3", "wav", "pcm"], "type": "string"},
                "sample_rate": {"type": "integer"},
                "mp3_bitrate": {"enum": [64, 128, 192], "type": "integer"},
                "latency": {"enum": ["normal", "balanced"], "type": "string"},
                "chunk_length": {"type": "integer"},
                "min_chunk_length": {"type": "integer"},
                "temperature": {"type": "number"},
                "top_p": {"type": "number"},
                "repetition_penalty": {"type": "number"},
                "max_new_tokens": {"type": "integer"},
                "normalize": {"type": "boolean"},
                "prosody": {"type": "object", "additionalProperties": True},
                "references": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 1,
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "required": ["audio", "text"],
                        "properties": {
                            "audio": {"type": "string", "format": "uri", "maxLength": 2048},
                            "text": {"type": "string", "minLength": 1, "maxLength": 10000},
                        },
                    },
                },
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "text": {"type": "string"},
            "reference_id": {
                "oneOf": [
                    {"type": "string"},
                    {"type": "array", "minItems": 1, "items": {"type": "string"}},
                ]
            },
            "format": {"enum": ["mp3", "wav", "pcm"], "type": "string"},
            "sample_rate": {"type": "integer"},
            "mp3_bitrate": {"enum": [64, 128, 192], "type": "integer"},
            "latency": {"enum": ["normal", "balanced"], "type": "string"},
            "chunk_length": {"type": "integer"},
            "min_chunk_length": {"type": "integer"},
            "temperature": {"type": "number"},
            "top_p": {"type": "number"},
            "repetition_penalty": {"type": "number"},
            "max_new_tokens": {"type": "integer"},
            "normalize": {"type": "boolean"},
            "prosody": {"type": "object", "additionalProperties": True},
            "references": {
                "type": "array",
                "minItems": 1,
                "maxItems": 1,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["audio", "text"],
                    "properties": {
                        "audio": {"type": "string", "format": "uri", "maxLength": 2048},
                        "text": {"type": "string", "minLength": 1, "maxLength": 10000},
                    },
                },
            },
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [
            {
                "in": "header",
                "name": "model",
                "schema": {"enum": ["s1", "s2-pro", "s2.1-pro"], "type": "string"},
                "required": False,
            }
        ],
        "defaults": {"model": "s2-pro", "format": "mp3"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "fish_search_voices": {
        "method": "GET",
        "path": "/fish/model",
        "operation": "voices",
        "schema": {"type": "object", "properties": {}},
        "properties": {},
        "parameters": [
            {"in": "query", "name": "page_size", "schema": {"type": "integer"}, "required": False},
            {
                "in": "query",
                "name": "page_number",
                "schema": {"type": "integer"},
                "required": False,
            },
            {"in": "query", "name": "title", "schema": {"type": "string"}, "required": False},
            {"in": "query", "name": "tag", "schema": {"type": "string"}, "required": False},
            {"in": "query", "name": "self", "schema": {"type": "boolean"}, "required": False},
            {"in": "query", "name": "author_id", "schema": {"type": "string"}, "required": False},
            {"in": "query", "name": "language", "schema": {"type": "string"}, "required": False},
            {
                "in": "query",
                "name": "title_language",
                "schema": {"type": "string"},
                "required": False,
            },
            {"in": "query", "name": "sort_by", "schema": {"type": "string"}, "required": False},
        ],
        "defaults": {"page_size": 10, "page_number": 1},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "fish_get_voice": {
        "method": "GET",
        "path": "/fish/model/{id}",
        "operation": "request",
        "schema": {"type": "object", "properties": {}},
        "properties": {},
        "parameters": [
            {"in": "path", "name": "id", "schema": {"type": "string"}, "required": True}
        ],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "fish_create_model": {
        "method": "POST",
        "path": "/fish/model",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["title", "voices"],
            "properties": {
                "title": {"type": "string"},
                "voices": {"type": "string"},
                "description": {"type": "string"},
                "cover_image": {"type": "string"},
                "tags": {"type": "array", "items": {"type": "string"}},
                "texts": {"type": "array", "items": {"type": "string"}},
                "enhance_audio_quality": {"type": "boolean"},
                "generate_sample": {"type": "boolean"},
            },
        },
        "properties": {
            "title": {"type": "string"},
            "voices": {"type": "string"},
            "description": {"type": "string"},
            "cover_image": {"type": "string"},
            "tags": {"type": "array", "items": {"type": "string"}},
            "texts": {"type": "array", "items": {"type": "string"}},
            "enhance_audio_quality": {"type": "boolean"},
            "generate_sample": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "fish_create_voice": {
        "method": "POST",
        "path": "/fish/voices",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["voice_url"],
            "properties": {
                "voice_url": {"type": "string"},
                "title": {"type": "string"},
                "description": {"type": "string"},
                "image_url": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "voice_url": {"type": "string"},
            "title": {"type": "string"},
            "description": {"type": "string"},
            "image_url": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "fish_task_retrieve": {
        "method": "POST",
        "path": "/fish/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "fish_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/fish/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
